power<-read.table("household_power_consumption.txt", header=TRUE, sep=";", colClasses = c("character","character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"), na.strings="?")
power<-transform(power, Date=as.Date(Date, format="%d/%m/%Y")) 
power2days<-subset(power, power$Date=="2007-02-01"|power$Date=="2007-02-02")
Time_Date <-paste(power2days$Date, power2days$Time, sep=" ")
Time_Date<-strptime(Time_Date, format="%Y-%m-%d %H:%M:%S", tz="GMT")
par(mfrow=c(2,2))
plot(Time_Date, power2days$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(Time_Date, power2days$Voltage, type="l", xlab="datetime", ylab="Voltabe")
plot(Time_Date, power2days$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(Time_Date, power2days$Sub_metering_2, col="red")
lines(Time_Date, power2days$Sub_metering_3, col="blue")
legend("topright",bty="n",lwd=1, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"))
plot(Time_Date, power2days$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png,"plot4.png")
dev.off()